//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OjExam.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OjExamEntities : DbContext
    {
        public OjExamEntities()
            : base("name=OjExamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> AdminSet { get; set; }
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<ClassTeacherCourser> ClassTeacherCourser { get; set; }
        public virtual DbSet<Courser> Courser { get; set; }
        public virtual DbSet<Exam> ExamSet { get; set; }
        public virtual DbSet<Grade> Grade { get; set; }
        public virtual DbSet<KnowPoint> KnowPointSet { get; set; }
        public virtual DbSet<Problem> Problem { get; set; }
        public virtual DbSet<Status> StatusSet { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
    }
}
