//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OjExam.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int Id { get; set; }
        public string Score { get; set; }
        public int StudentId { get; set; }
        public int ExamId { get; set; }
        public string Problems { get; set; }
        public string Answers { get; set; }
        public string Status { get; set; }
        public short DelFlag { get; set; }
    
        public virtual Exam ExamSet { get; set; }
        public virtual Student Student { get; set; }
    }
}
